#FUNÇÃO ALTERNATIVA PARA BUSCAR PALAVRAS EM UM PDF. USA A LIB PYPDF3
#ESSA LIB POSSIU OUTRAS FUNCIONALIDADES PARA SEREM IMPLEMENTADAS FUTURAMENTE
#PORÉM, ELA NÃO FOI USADA, POIS NÃO POSSUI A FUNÇÃO HIGHLIGHT, POR ISSO USEI O FITZ PARA ESSE PROJETO

import PyPDF3
import re

OMs = ['GAP GL','GAP-GL','GRUPAMENTO DE APOIO DO GALEÃO','GAPGL',
  'PAMA GL','PAMA-GL','PARQUE DE MATERIAL AERONÁUTICO DO GALEÃO','PAMA GL','PAMAGL', 
  'BAGL','BASE AÉREA DO GALEÃO','BAGL_ANTIGA'
  'CMRJ','COLÉGIO MILITAR DO RIO DE JANEIRO',
  '1 CJM','1° CJM','PRIMEIRA CIRCUNSCRIÇÃO JUDICIÁRIA MILITAR','1CJM','1°CJM',
  'CEMAL','CENTRO DE MEDICINA AEROESPACIAL',    
  'BINFAE GL','BINFAE-GL','BATALHÃO DE INFANTARIA DA AERONÁUTICA ESPECIAL DO GALEÃO','BINFAEGL',
   'CCA RJ','CENTRO DE COMPUTAÇÃO DA AERONÁUTICA DO RIO DE JANEIRO','CCARJ',    
   'PAGL','PREFEITURA DE AERONÁUTICA DO GALEÃO',
   '3 ETA','3° ETA','TERCEIRO ETA','3ETA','3°ETA'
   'GOP GL','GOP-GL','GRUPO OPERACIONAL DO GALEÃO','GOPGL','GOPGL',
   'GLOG GL','GLOG-GL','GRUPO LOGÍSTICO DO GALEÃO','GLOGGL',
   'MTAB','MISSÃO TÉCNICA AERONÁUTICA BRASILEIRA NA BOLÍVIA',
   'DIRAP','DIRETORIA DE ADMINISTRAÇÃO DO PESSOAL',
   'DIRSA','DIRETORIA DE SAÚDE DA AERONÁUTICA',
   'CGABEG','CASA GERONTOLÓGICA DE AERONÁUTICA BRIGADEIRO EDUARDO GOMES',
   'CBNB','COLEGIO BRIGADEIRO NEWTON BRAGA',
   'SERIPA III','TERCEIRO SERVIÇO REGIONAL DE INVESTIGAÇÃO E PREVENÇÃO DE ACIDENTES AERONÁUTICOS','SERIPAIII',
   'ESG','ESCOLA SUPERIOR DE GUERRA',
   'PAMB RJ','PAMB-RJ','PARQUE DE MATERIAL BÉLICO DA AERONÁUTICA DO RIO DE JANEIRO','PAMBRJ',
   'DTCEA-GL','DTCEA GL','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO DO GALEÃO','DTCEAGL',
   '1/2 GT','1°/2° GT','PRIMEIRO ESQUADRÃO DO SEGUNDO GRUPO DE TRANSPORTE','1/2GT','1°/2°GT','1º/2º GT','1º/2ºGT'
   '1 GCC','PRIMEIRO GRUPO DE COMUNICAÇÕES E CONTROLE','1° GCC','1GCC','1°GCC','1ºGCC','1º GCC'
   '1/1 GT','1°/1° GT','PRIMEIRO ESQUADRÃO DO PRIMEIRO GRUPO DE TRANSPORTE','1/1GT','1°/1°GT','1º/1º GT','1º/1ºGT'
   '2/2 GT','2°/2° GT','SEGUNDO ESQUADRÃO DO SEGUNDO GRUPO DE TRANSPORTE','2°/2°GT','2/2GT','2º/2º GT','2º/2ºGT'
   'LAQFA','LABORATÓRIO QUÍMICO-FARMACÊUTICO DA AERONÁUTICA',
   'CTLA','CENTRO DE TRANSPORTE LOGÍSTICO DA AERONÁUTICA',
   'ALA 11','BASE AÉREA DO GALEÃO','ALA11',
   'CIMAER','CENTRO INTEGRADO DE METEOROLOGIA DA AERONÁUTICA',
   'CAE','CENTRO DE AQUISIÇÕES ESPECÍFICAS',
   'COPE-S','CENTRO DE OPERAÇÕES ESPACIAIS SECUNDÁRIO','COPE S',
   'GSD-GL','GRUPO DE SEGURANÇA E DEFESA DO GALEÃO','GSDGL',
   'HFAG','HOSPITAL DE FORÇA AÉREA DO GALEÃO']

def BuscaOMsApoiadas(*args):
  BcadoDia = open(*args, 'rb')
  leitura = PyPDF3.PdfFileReader(BcadoDia)

  ltotal = leitura.getNumPages()
  print('O numero de paginas do BCA do DIA é: ',ltotal)

  j=0
  while j < ltotal:
    i=0
    pagina = leitura.getPage(j) #Obtem a página atual do PDF
    materia = pagina.extractText() #Extrai o texto da página atual
    numPage=leitura.getPageNumber(pagina) #Obtem o numero da página atual
    m = materia  
    while i < len(OMs):
      OM_procurada = re.findall(OMs[i],m)
      if OM_procurada != []:
        print('A OM Apoiada: ',set(OM_procurada),'foi encontrada ',len(OM_procurada),' vez(es)', 'na página', numPage+1)       
      i=i+1      
    j=j+1
    return OM_procurada

BuscaOMsApoiadas('bca_23_02-02-2023.pdf')